version: '3.1'

services:

  db:
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_USER=tech
      - POSTGRES_PASSWORD=tech
    volumes:
      - "data-db:/var/lib/postgresql/data"
  srv:
    image: terminus
    volumes:
      - ./app:/code/app
    ports: 
      - 80:80
    depends_on:
      - db

volumes:
  data-db: